requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Pricing*
  ignore:
    - Pricing::Configuration*
    - Pricing::Discounts::NoPercentageDiscount#discount
    - Pricing::Test*
